# Generated by Django 4.1.1 on 2022-09-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('street', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='street',
            old_name='city_id',
            new_name='city',
        ),
    ]
