version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    ports:
      - "8088:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  web:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - db
volumes:
  pgdbdata: null