# Generated by Django 4.1.1 on 2022-09-23 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('street', '0001_initial'),
        ('city', '0002_alter_city_options_alter_city_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название магазина')),
                ('start_time', models.CharField(max_length=5, verbose_name='Время открытия')),
                ('end_time', models.CharField(max_length=5, verbose_name='Время закрытия')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city', verbose_name='id города')),
                ('street_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street.street', verbose_name='id улицы')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
    ]
