# Generated by Django 4.1.1 on 2022-10-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_rename_city_id_shop_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='end_time',
            field=models.TimeField(verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='start_time',
            field=models.TimeField(verbose_name='Время открытия'),
        ),
    ]
